package onlineticketing.datasource;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import onlineticketing.domain.Seat;

public class SeatMapper {
	
	/**
	 * Find a seat by seat ID
	 * @param seatId  the ID of a seat
	 * @return the  seat which has the seat Id passed in
	 */
	public static Seat findSeatById (int seatId) {
		
		String findSeatString = "SELECT * FROM ONLINETICKETING.SEATS "
				+ "WHERE SEATID = " + seatId;
		PreparedStatement findSeatStatement = DBConnection.prepare(findSeatString);
		Seat seat = null;
		
		try {
			ResultSet rs = findSeatStatement.executeQuery();
			seat = loadSeat(rs);
			
			DBConnection.close(findSeatStatement);
			rs.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return seat;
	}
	
	/**
	 * Find all the seats in a screening room
	 * @param screeningRoomId  the input screening room id
	 * @return a list of all the seats in the screening room with input screening room id
	 */
	public static ArrayList<Seat> findSeatsByScreeningRoomId (int screeningRoomId) {
		
		String findSeatsString = "SELECT * FROM ONLINETICKETING.SEATS "
				+ "WHERE SCREENINGROOMID = " + screeningRoomId;
		PreparedStatement findSeatsStatement = DBConnection.prepare(findSeatsString);
		ArrayList<Seat> seatList = new ArrayList<Seat>();
		
		try {
			ResultSet rs = findSeatsStatement.executeQuery();
			
			while(rs.next()) {
				seatList.add(loadSeat(rs));
			}
			
			DBConnection.close(findSeatsStatement);
			rs.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return seatList;
	}
	
	/**
	 * Generate a seat object from a resultset
	 * @param rs  the resultset of a seat
	 * @return the seat object generated by the resultset
	 */
	public static Seat loadSeat(ResultSet rs) {
		Seat seat = null;
		
		try {
			int seatId = rs.getInt("SEATID");
			int screeningRoomId = rs.getInt("SCREENINGROOMID");
			String seatNumber = rs.getString("SEATNUMBER");
			seat = new Seat(seatId, screeningRoomId, seatNumber);
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return seat;
	}
}
