CREATE SCHEMA IF NOT EXISTS onlineticketing ;

DROP TABLE IF EXISTS onlineticketing.films;
DROP TABLE IF EXISTS onlineticketing.schedules;
DROP TABLE IF EXISTS onlineticketing.seats;
DROP TABLE IF EXISTS onlineticketing.users;
DROP TABLE IF EXISTS onlineticketing.tickets;
DROP TABLE IF EXISTS onlineticketing.orders;

CREATE TABLE onlineticketing.films(
	filmid INT NOT NULL,
	title VARCHAR(100),
	description TEXT,
	poster VARCHAR(50),
	runningtime VARCHAR(50),
	director VARCHAR(100),
	maincast VARCHAR(200),
	genre VARCHAR(100),
	PRIMARY KEY (filmid)
);

CREATE TABLE onlineticketing.schedules(
	scheduleid VARCHAR(50) NOT NULL,
	screeningroomid INT,
	starttime DATE,
	endtime DATE,
	price REAL,
	filmid INT,
	PRIMARY KEY (scheduleid)
);

CREATE TABLE onlineticketing.seats(
	seatid INT NOT NULL,
	screeningroomid INT,
	seatnumber VARCHAR(50),
	PRIMARY KEY (seatid)
);

CREATE TABLE onlineticketing.tickets(
	ticketid VARCHAR(50) NOT NULL,
	sold SMALLINT,
	scheduleid VARCHAR(50),
	seatid INT,
	orderid INT,
	PRIMARY KEY (ticketid)
);

CREATE TABLE onlineticketing.orders(
	orderid SERIAL NOT NULL,
	status INT,
	createtime DATE,
	ticketinfo VARCHAR(100),
	payment REAL,
	customerid INT,
	PRIMARY KEY (orderid)
);

CREATE TABLE onlineticketing.users(
	userid INT NOT NULL,
	username VARCHAR(50),
	password VARCHAR(50),
	phonenumber INT,
	permission SMALLINT,
	PRIMARY KEY (userid)
);

INSERT INTO onlineticketing.users (userid, username, password, permission)
VALUES (0, 'admin', 'admin', 0);
INSERT INTO onlineticketing.users (userid, username, password, phonenumber, permission)
VALUES (1, 'user1', '123456', 0478563496, 0);

INSERT INTO onlineticketing.orders (status, createtime, ticketinfo, payment, customerid) 
VALUES (0,'2018-08-26','example information',100,1);

INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1001,1,'A1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1002,1,'A2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1003,1,'A3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1004,1,'A4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1005,1,'A5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1006,1,'A6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1007,1,'A7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1008,1,'A8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1009,1,'A9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1010,1,'A10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1011,1,'A11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1012,1,'A12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1013,1,'A13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1014,1,'A14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1015,1,'A15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1016,1,'A16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1017,1,'B1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1018,1,'B2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1019,1,'B3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1020,1,'B4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1021,1,'B5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1022,1,'B6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1023,1,'B7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1024,1,'B8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1025,1,'B9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1026,1,'B10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1027,1,'B11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1028,1,'B12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1029,1,'B13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1030,1,'B14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1031,1,'B15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1032,1,'B16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1033,1,'C1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1034,1,'C2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1035,1,'C3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1036,1,'C4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1037,1,'C5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1038,1,'C6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1039,1,'C7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1040,1,'C8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1041,1,'C9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1042,1,'C10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1043,1,'C11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1044,1,'C12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1045,1,'C13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1046,1,'C14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1047,1,'C15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1048,1,'C16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1049,1,'D1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1050,1,'D2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1051,1,'D3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1052,1,'D4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1053,1,'D5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1054,1,'D6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1055,1,'D7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1056,1,'D8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1057,1,'D9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1058,1,'D10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1059,1,'D11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1060,1,'D12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1061,1,'D13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1062,1,'D14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1063,1,'D15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1064,1,'D16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1065,1,'E1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1066,1,'E2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1067,1,'E3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1068,1,'E4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1069,1,'E5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1070,1,'E6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1071,1,'E7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1072,1,'E8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1073,1,'E9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1074,1,'E10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1075,1,'E11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1076,1,'E12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1077,1,'E13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1078,1,'E14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1079,1,'E15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1080,1,'E16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1081,1,'F1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1082,1,'F2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1083,1,'F3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1084,1,'F4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1085,1,'F5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1086,1,'F6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1087,1,'F7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1088,1,'F8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1089,1,'F9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1090,1,'F10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1091,1,'F11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1092,1,'F12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1093,1,'F13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1094,1,'F14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1095,1,'F15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1096,1,'F16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1097,1,'G1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1098,1,'G2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1099,1,'G3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1100,1,'G4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1101,1,'G5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1102,1,'G6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1103,1,'G7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1104,1,'G8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1105,1,'G9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1106,1,'G10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1107,1,'G11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1108,1,'G12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1109,1,'G13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1110,1,'G14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1111,1,'G15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1112,1,'G16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1113,1,'H1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1114,1,'H2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1115,1,'H3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1116,1,'H4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1117,1,'H5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1118,1,'H6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1119,1,'H7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1120,1,'H8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1121,1,'H9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1122,1,'H10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1123,1,'H11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1124,1,'H12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1125,1,'H13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1126,1,'H14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1127,1,'H15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(1128,1,'H16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2001,2,'A1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2002,2,'A2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2003,2,'A3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2004,2,'A4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2005,2,'A5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2006,2,'A6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2007,2,'A7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2008,2,'A8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2009,2,'A9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2010,2,'A10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2011,2,'A11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2012,2,'A12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2013,2,'A13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2014,2,'A14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2015,2,'A15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2016,2,'A16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2017,2,'B1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2018,2,'B2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2019,2,'B3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2020,2,'B4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2021,2,'B5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2022,2,'B6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2023,2,'B7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2024,2,'B8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2025,2,'B9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2026,2,'B10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2027,2,'B11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2028,2,'B12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2029,2,'B13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2030,2,'B14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2031,2,'B15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2032,2,'B16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2033,2,'C1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2034,2,'C2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2035,2,'C3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2036,2,'C4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2037,2,'C5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2038,2,'C6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2039,2,'C7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2040,2,'C8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2041,2,'C9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2042,2,'C10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2043,2,'C11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2044,2,'C12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2045,2,'C13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2046,2,'C14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2047,2,'C15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2048,2,'C16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2049,2,'D1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2050,2,'D2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2051,2,'D3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2052,2,'D4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2053,2,'D5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2054,2,'D6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2055,2,'D7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2056,2,'D8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2057,2,'D9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2058,2,'D10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2059,2,'D11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2060,2,'D12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2061,2,'D13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2062,2,'D14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2063,2,'D15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2064,2,'D16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2065,2,'E1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2066,2,'E2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2067,2,'E3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2068,2,'E4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2069,2,'E5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2070,2,'E6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2071,2,'E7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2072,2,'E8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2073,2,'E9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2074,2,'E10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2075,2,'E11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2076,2,'E12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2077,2,'E13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2078,2,'E14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2079,2,'E15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2080,2,'E16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2081,2,'F1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2082,2,'F2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2083,2,'F3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2084,2,'F4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2085,2,'F5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2086,2,'F6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2087,2,'F7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2088,2,'F8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2089,2,'F9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2090,2,'F10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2091,2,'F11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2092,2,'F12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2093,2,'F13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2094,2,'F14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2095,2,'F15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2096,2,'F16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2097,2,'G1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2098,2,'G2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2099,2,'G3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2100,2,'G4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2101,2,'G5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2102,2,'G6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2103,2,'G7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2104,2,'G8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2105,2,'G9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2106,2,'G10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2107,2,'G11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2108,2,'G12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2109,2,'G13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2110,2,'G14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2111,2,'G15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2112,2,'G16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2113,2,'H1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2114,2,'H2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2115,2,'H3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2116,2,'H4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2117,2,'H5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2118,2,'H6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2119,2,'H7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2120,2,'H8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2121,2,'H9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2122,2,'H10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2123,2,'H11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2124,2,'H12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2125,2,'H13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2126,2,'H14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2127,2,'H15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(2128,2,'H16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3001,3,'A1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3002,3,'A2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3003,3,'A3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3004,3,'A4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3005,3,'A5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3006,3,'A6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3007,3,'A7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3008,3,'A8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3009,3,'A9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3010,3,'A10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3011,3,'A11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3012,3,'A12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3013,3,'A13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3014,3,'A14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3015,3,'A15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3016,3,'A16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3017,3,'B1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3018,3,'B2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3019,3,'B3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3020,3,'B4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3021,3,'B5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3022,3,'B6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3023,3,'B7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3024,3,'B8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3025,3,'B9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3026,3,'B10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3027,3,'B11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3028,3,'B12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3029,3,'B13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3030,3,'B14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3031,3,'B15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3032,3,'B16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3033,3,'C1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3034,3,'C2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3035,3,'C3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3036,3,'C4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3037,3,'C5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3038,3,'C6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3039,3,'C7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3040,3,'C8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3041,3,'C9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3042,3,'C10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3043,3,'C11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3044,3,'C12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3045,3,'C13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3046,3,'C14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3047,3,'C15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3048,3,'C16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3049,3,'D1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3050,3,'D2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3051,3,'D3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3052,3,'D4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3053,3,'D5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3054,3,'D6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3055,3,'D7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3056,3,'D8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3057,3,'D9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3058,3,'D10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3059,3,'D11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3060,3,'D12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3061,3,'D13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3062,3,'D14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3063,3,'D15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3064,3,'D16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3065,3,'E1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3066,3,'E2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3067,3,'E3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3068,3,'E4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3069,3,'E5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3070,3,'E6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3071,3,'E7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3072,3,'E8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3073,3,'E9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3074,3,'E10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3075,3,'E11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3076,3,'E12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3077,3,'E13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3078,3,'E14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3079,3,'E15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3080,3,'E16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3081,3,'F1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3082,3,'F2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3083,3,'F3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3084,3,'F4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3085,3,'F5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3086,3,'F6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3087,3,'F7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3088,3,'F8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3089,3,'F9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3090,3,'F10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3091,3,'F11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3092,3,'F12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3093,3,'F13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3094,3,'F14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3095,3,'F15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3096,3,'F16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3097,3,'G1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3098,3,'G2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3099,3,'G3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3100,3,'G4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3101,3,'G5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3102,3,'G6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3103,3,'G7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3104,3,'G8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3105,3,'G9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3106,3,'G10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3107,3,'G11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3108,3,'G12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3109,3,'G13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3110,3,'G14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3111,3,'G15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3112,3,'G16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3113,3,'H1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3114,3,'H2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3115,3,'H3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3116,3,'H4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3117,3,'H5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3118,3,'H6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3119,3,'H7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3120,3,'H8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3121,3,'H9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3122,3,'H10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3123,3,'H11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3124,3,'H12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3125,3,'H13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3126,3,'H14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3127,3,'H15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(3128,3,'H16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4001,4,'A1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4002,4,'A2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4003,4,'A3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4004,4,'A4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4005,4,'A5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4006,4,'A6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4007,4,'A7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4008,4,'A8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4009,4,'A9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4010,4,'A10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4011,4,'A11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4012,4,'A12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4013,4,'A13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4014,4,'A14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4015,4,'A15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4016,4,'A16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4017,4,'B1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4018,4,'B2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4019,4,'B3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4020,4,'B4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4021,4,'B5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4022,4,'B6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4023,4,'B7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4024,4,'B8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4025,4,'B9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4026,4,'B10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4027,4,'B11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4028,4,'B12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4029,4,'B13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4030,4,'B14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4031,4,'B15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4032,4,'B16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4033,4,'C1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4034,4,'C2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4035,4,'C3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4036,4,'C4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4037,4,'C5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4038,4,'C6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4039,4,'C7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4040,4,'C8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4041,4,'C9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4042,4,'C10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4043,4,'C11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4044,4,'C12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4045,4,'C13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4046,4,'C14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4047,4,'C15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4048,4,'C16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4049,4,'D1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4050,4,'D2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4051,4,'D3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4052,4,'D4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4053,4,'D5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4054,4,'D6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4055,4,'D7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4056,4,'D8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4057,4,'D9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4058,4,'D10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4059,4,'D11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4060,4,'D12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4061,4,'D13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4062,4,'D14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4063,4,'D15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4064,4,'D16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4065,4,'E1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4066,4,'E2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4067,4,'E3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4068,4,'E4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4069,4,'E5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4070,4,'E6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4071,4,'E7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4072,4,'E8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4073,4,'E9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4074,4,'E10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4075,4,'E11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4076,4,'E12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4077,4,'E13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4078,4,'E14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4079,4,'E15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4080,4,'E16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4081,4,'F1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4082,4,'F2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4083,4,'F3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4084,4,'F4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4085,4,'F5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4086,4,'F6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4087,4,'F7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4088,4,'F8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4089,4,'F9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4090,4,'F10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4091,4,'F11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4092,4,'F12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4093,4,'F13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4094,4,'F14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4095,4,'F15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4096,4,'F16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4097,4,'G1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4098,4,'G2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4099,4,'G3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4100,4,'G4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4101,4,'G5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4102,4,'G6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4103,4,'G7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4104,4,'G8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4105,4,'G9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4106,4,'G10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4107,4,'G11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4108,4,'G12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4109,4,'G13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4110,4,'G14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4111,4,'G15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4112,4,'G16');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4113,4,'H1');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4114,4,'H2');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4115,4,'H3');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4116,4,'H4');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4117,4,'H5');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4118,4,'H6');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4119,4,'H7');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4120,4,'H8');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4121,4,'H9');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4122,4,'H10');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4123,4,'H11');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4124,4,'H12');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4125,4,'H13');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4126,4,'H14');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4127,4,'H15');
INSERT INTO ONLINETICKETING.SEATS(SEATID,SCREENINGROOMID,SEATNUMBER) VALUES(4128,4,'H16');